### ISSUE TITLE
批量上传文件不支持同key

### ISSUE THREAD

**Issue by liuxiaodongLXD** [admin4j/common-http#3]
批量上传文件时是有可能key都叫"file"的，都叫"file"key 值可以是多个文件, 当然此处的"file"key名只是我举的例子，但此封装不支持这种模式，可以考虑增加支持此模式

**Comment by andanyoung** [comment]
这种场景很少使用。可以使用`Response upload(String url, Map<String, Object> formParams)` formParams 传入 List<File> 的方式使用。

**Comment by andanyoung** [comment]
这种场景很少使用。可以使用`Response upload(String url, Map<String, Object> formParams)` formParams 传入 List<File> 的方式使用。
